server:
  port: 8091

spring:
  application:
    name: consumer

#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: practice-group-1
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#
#      properties:
#        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.trusted.packages: com.example.consumer.model
#        spring.json.value.default.type: com.example.consumer.model.Course